### ISSUE TITLE
Yarn fails to install packages

### ISSUE THREAD

**Issue by Naxdy** [NayamAmarshe/DeskCut#1]
Hey, I'm trying to build from source so I can create a PKGBUILD for the AUR. However, trying to install dependencies leaves me with this error:

```
yarn install v1.22.17
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/asarUnpack: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/home/naxdy/git/DeskCut/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I have `node` (via `nvm`), `yarn` and `asar` installed. Are there any other dependencies I may be missing?

**Comment by NayamAmarshe** [comment]
Hi, sorry for the trouble. I have fixed the issue. It was being caused because I added asarUnpack in the wrong place in package.json.
