### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by TechnologyClassroom** [NayamAmarshe/DeskCut#2]
I see the project is GPLv2.  Is this GPL-2.0-OR-LATER or GPL-2.0-ONLY?

I would recommend adding a LICENSE file to make the license clearly visible for the first page view.

Edit: Typo

**Comment by NayamAmarshe** [comment]
I'll update the license, thanks for reminding me

**Comment by NayamAmarshe** [comment]
Done!

**Comment by TechnologyClassroom** [comment]
Excellent!  What about which version of GPLv2?

package.json says `  "license": "GPLv2",`

Is this GPL-2.0-OR-LATER or GPL-2.0-ONLY?

**Comment by NayamAmarshe** [comment]
> Excellent! What about which version of GPLv2?
> 
> package.json says ` "license": "GPLv2",`
> 
> Is this GPL-2.0-OR-LATER or GPL-2.0-ONLY?

This is GPL-2.0 ONLY. I also added that on the snap store but it doesn't mention only or later.
